project_id = "eheiujcuirpciqffcltr"

[functions.calculate-shipping]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false