project_id = "eheiujcuirpciqffcltr"

[functions.calculate-shipping]
verify_jwt = false

[functions.create-abacatepay-checkout]
verify_jwt = false

[functions.abacatepay-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-status-update-email]
verify_jwt = false

[functions.create-mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.finalize-pickup-order]
verify_jwt = false
